### ISSUE TITLE
Package conflict

### ISSUE THREAD

**Issue by alexanderlebedev** [iuscommunity-pkg/haproxy18u#3]
Hello! Thanks for package! But why is there a conflict declared in the package specification? In most cases, HAproxy supports backward compatibility. How can I update HAproxy without downtime?

**Comment by carlwgeorge** [comment]
haproxy18u is a [safe replacement package](https://ius.io/Usage/#safe-replacement-packages).  It completely replaces the stock haproxy package and cannot be installed at the same time due to placing files at the same locations.  Please see our [usage guide](https://ius.io/Usage/) for instructions on how to update from stock haproxy to haproxy18u (or from one IUS package to the next major version, i.e. haproxy17u to haproxy18u).
